backend:
  name: github
  repo: alexmuro/fivekill

media_folder: static/assets


collections:
  - name: press
    label: press quotes
    folder: content/press
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Source", name: "Source", widget: "string"}
      - {label: "Blurb", name: "Blurb", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Artist", name: "artist-name", widget: "string"}
      - {label: "reslease", name: "release-name", widget: "string"}
  - name: news 
    label: news
    folder: content/news
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Path", name: "path", widget: "string", default: "/news/"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "coverImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: artists
    label: artists
    folder: content/artists
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Artist Name", name: "name", widget: "string"}
      - {label: "Path", name: "path", widget: "string", default: "/artists/"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Press Photo", name: "pressPhoto", widget: "image"}
      - {label: "artistId", name: "band-id", widget: "string"}
      - {label: "website", name: "website", widget: "string", required: false}
      - {label: "spotify", name: "spotify", widget: "string", required: false}
      - {label: "bandcamp", name: "bandcamp", widget: "string", required: false}
      - {label: "facebook", name: "facebook", widget: "string", required: false}
      - {label: "twitter", name: "facebook", widget: "string", required: false}
      - {label: "instagram", name: "instagram", widget: "string", required: false}
      - {label: "booking", name: "booking", widget: "string", required: false}
      - {label: "press", name: "press", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: releases
    label: releases
    folder: content/releases
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Path", name: "path", widget: "string", default: "/releases/"}
      - {label: "Street Date", name: "date", widget: "datetime"}
      - {label: "Album Cover", name: "coverImage", widget: "image"}
      - {label: "Release Title", name: "title", widget: "string"}
      - {label: "releaseNumber", name: "releaseNumber", widget: "string"}
      - {label: "artist", name: "artist", widget: "string"}
      - {label: "band-id", name: "band-id", widget: "string"}
      - {label: "spotify", name: "spotify", widget: "string", required: false}
      - {label: "bandcamp", name: "bandcamp", widget: "string", required: false}
      - {label: "soundcloud", name: "soundcloud", widget: "string", required: false}
      - {label: "itunes", name: "itunes", widget: "string", required: false}
      - {label: "googleplay", name: "googleplay", widget: "string", required: false}
      - {label: "amazon", name: "amazon", widget: "string", required: false}
      - {label: "releaseType", name: "releaseType", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}